version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: freight
      POSTGRES_PASSWORD: freight
      POSTGRES_DB: freight
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
volumes:
  db_data:
